spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format-sql: true
        default_batch_fetch_size: 20
        jbdc.batch_size: 20
    defer-datasource-initialization: true
  datasource:
    url: jdbc:h2:mem:voting
    username: sa
    password:
  h2.console.enabled: true
  h2.console.path: /h2-console